# Generated by Django 4.0.5 on 2022-06-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0006_rename_mine_type_resourcemodel_mime_type'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
    ]
