# Generated by Django 4.0.5 on 2022-06-13 07:29

import biblishelf_web.apps.book.models
import biblishelf_web.apps.main.fields
import biblishelf_web.apps.main.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_book', '0004_remove_bookmodel_set_book_remove_bookmodel_set_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover',
            field=biblishelf_web.apps.main.fields.PortableImageField(blank=True, null=True, storage=biblishelf_web.apps.main.storage.PortableStorage, upload_to=biblishelf_web.apps.book.models._book_cover_uploader, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookpublishing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
