-   repo: git://github.com/pre-commit/mirrors-isort
    sha: v4.2.15  # Use the sha / tag you want to point at
    hooks:
    -   id: isort
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0  # Use the ref you want to point at
    hooks:
    -   id: autopep8-wrapper
    -   id: check-ast
   # -   id: trailing-whitespace
    -   id: flake8
    -   id: requirements-txt-fixer
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: forbid-new-submodules
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.8.2  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
