# Generated by Django 4.0.5 on 2022-06-14 17:41

import biblishelf_web.apps.main.fields
import biblishelf_web.apps.main.storage
import biblishelf_web.apps.plugins.book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_book', '0006_alter_bookmodel_cover_alter_bookmodel_douban_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='douban_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='page_number',
            field=models.PositiveIntegerField(default=0, help_text='resource page number'),
        ),
        migrations.CreateModel(
            name='IsbnBookInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('isbn', models.CharField(max_length=64, unique=True)),
                ('douban_id', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('cover', biblishelf_web.apps.main.fields.PortableImageField(blank=True, default='', storage=biblishelf_web.apps.main.storage.PortableStorage, upload_to=biblishelf_web.apps.plugins.book.models._book_cover_uploader, verbose_name='cover')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblishelf_book.bookpublishing')),
            ],
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='isbn_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblishelf_book.isbnbookinfomodel'),
        ),
    ]
