# Generated by Django 4.0.5 on 2022-06-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_book', '0007_alter_bookmodel_douban_id_alter_bookmodel_isbn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='isbn',
            new_name='isbn_str',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='isbn_ref',
            new_name='isbn',
        ),
    ]
