# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 09:10
from __future__ import unicode_literals

import biblishelf_book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblishelf_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('douban_id', models.CharField(blank=True, max_length=64, null=True)),
                ('set_type', models.CharField(blank=True, choices=[('series', 'series'), ('same', 'same')], max_length=8, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=biblishelf_book.models._book_cover_uploader, verbose_name='cover')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookPublishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblishelf_book.BookPublishing'),
        ),
        migrations.AddField(
            model_name='book',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblishelf_main.ResourceMap'),
        ),
        migrations.AddField(
            model_name='book',
            name='set_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_books', to='biblishelf_book.Book'),
        ),
    ]
