# Generated by Django 4.0.5 on 2022-06-07 16:22

import biblishelf_book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblishelf_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('douban_id', models.CharField(blank=True, max_length=64, null=True)),
                ('set_type', models.CharField(blank=True, choices=[('series', 'series'), ('same', 'same')], max_length=8, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=biblishelf_book.models._book_cover_uploader, verbose_name='cover')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblishelf_book.bookpublishing')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblishelf_main.resource')),
                ('set_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_books', to='biblishelf_book.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
