# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblishelf_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('douban_id', models.CharField(blank=True, max_length=64, null=True)),
                ('set_type', models.CharField(blank=True, choices=[('series', 'series'), ('same', 'same')], max_length=8, null=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='biblishelf_main.ResourceMap')),
                ('set_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_books', to='biblishelf_book.Book')),
            ],
        ),
    ]
