# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:10
from __future__ import unicode_literals

import biblishelf_book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=biblishelf_book.models._book_cover_uploader, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='info'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblishelf_main.ResourceMap'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblishelf_book.BookPublishing'),
        ),
    ]
