# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashSha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frag1', models.CharField(max_length=254)),
                ('frag2', models.CharField(max_length=254)),
                ('frag3', models.CharField(max_length=130)),
                ('frag4', models.CharField(max_length=4)),
                ('frag5', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_modify_time', models.DateTimeField()),
                ('file_create_time', models.DateTimeField()),
                ('file_access_time', models.DateTimeField()),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_portable', models.BooleanField(default=True)),
                ('media_type', models.CharField(choices=[('disc', 'disc'), ('ssd', 'ssd'), ('usb-disc', 'usb-disc'), ('cd', 'cd'), ('usb-ssd', 'usb-ssd'), ('tf/sd', 'tf-sd'), ('samba', 'samba'), ('cloud', 'cloud')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('sha1', models.CharField(blank=True, max_length=224, null=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
                ('ed2k_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('mine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblishelf_main.MineType')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblishelf_main.Repo'),
        ),
        migrations.AddField(
            model_name='path',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblishelf_main.Resource'),
        ),
        migrations.AddField(
            model_name='hashsha',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblishelf_main.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('size', 'ed2k_hash'), ('size', 'sha1'), ('size', 'md5')]),
        ),
        migrations.AlterUniqueTogether(
            name='path',
            unique_together=set([('repo', 'resource', 'path')]),
        ),
    ]
