# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWatchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('uuid', models.CharField(max_length=128, verbose_name='Volumn')),
                ('type', models.CharField(blank=True, choices=[('mount', 'mount'), ('set', 'set')], max_length=32, null=True)),
                ('dev_path', models.CharField(blank=True, max_length=128, null=True)),
                ('fs', models.CharField(blank=True, max_length=32, null=True)),
                ('extend_info', models.TextField(blank=True, null=True)),
                ('online_status', models.NullBooleanField()),
                ('last_online_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=0)),
                ('sha', models.CharField(blank=True, max_length=150, null=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mine_type', models.CharField(blank=True, max_length=32, null=True)),
                ('ed2k_hash', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('create_time', models.DateTimeField(blank=True, help_text='help check out danger file', null=True)),
                ('modify_time', models.DateTimeField(blank=True, help_text='help check out danger file', null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resources', to='biblishelf_main.Repo')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Map', to='biblishelf_main.Resource')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('size', 'sha')]),
        ),
        migrations.AddField(
            model_name='configwatcharea',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WatchAreas', to='biblishelf_main.Repo'),
        ),
    ]
