# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWatchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uuid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=0)),
                ('path', models.FilePathField()),
                ('sha', models.CharField(max_length=150)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resources', to='biblishelf_main.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='configwatcharea',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WatchAreas', to='biblishelf_main.Driver'),
        ),
    ]
