# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configwatcharea',
            name='path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='resourcemap',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
