# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0002_auto_20160912_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=0)),
                ('sha', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resourcemap',
            name='sha',
        ),
        migrations.RemoveField(
            model_name='resourcemap',
            name='size',
        ),
        migrations.AlterField(
            model_name='driver',
            name='uuid',
            field=models.CharField(max_length=128, verbose_name='Volumn'),
        ),
        migrations.AddField(
            model_name='resourcemap',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Map', to='biblishelf_main.Resource'),
        ),
    ]
