# Generated by Django 4.0.5 on 2022-06-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0002_rename_hashsha_hashshamodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
