# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0003_driver_recode_fs'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dev_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
