# Generated by Django 4.0.5 on 2022-06-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0003_repomodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minetypemodel',
            old_name='mine',
            new_name='mime',
        ),
    ]
