# Generated by Django 4.0.5 on 2022-06-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0004_rename_mine_minetypemodel_mime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MineTypeModel',
            new_name='MimeTypeModel',
        ),
    ]
