# Generated by Django 4.0.5 on 2022-06-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0005_rename_minetypemodel_mimetypemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcemodel',
            old_name='mine_type',
            new_name='mime_type',
        ),
    ]
