# Generated by Django 4.0.5 on 2022-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0007_alter_hashshamodel_id_alter_mimetypemodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathmodel',
            name='is_exist',
            field=models.BooleanField(default=True),
        ),
    ]
