# Generated by Django 4.0.5 on 2022-06-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblishelf_main', '0008_pathmodel_is_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='auto_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RepoHashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=254)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblishelf_main.repomodel')),
            ],
        ),
    ]
